language: python

python:
  - "3.7"

before_script:
  - python --version
  - |
    for fn in custom-resource/*; do
      printf "\n--> Installing %s requirements...\n" ${fn}
      pip install -r ${fn}/requirements.txt -t ${fn}
    done
  - pip install -r requirements.txt

script:
  - |
    if [ $TRAVIS_PULL_REQUEST == true ] && [ $TRAVIS_BRANCH != "master" ]; then
      VERSION="v$(cat main/main.template | shyaml get-value Globals.Function.Environment.Variables.VERSION)"
      git tag $VERSION
    fi

before_deploy:
  - mkdir -p ~/.aws
  - |
    cat >> ~/.aws/config <<EOF
    [profile publisher]
    credential_source=Environment
    role_arn=${ROLE_ARN}
    duration_seconds=900
    EOF
  - VERSION="v$(cat main/main.template | shyaml get-value Globals.Function.Environment.Variables.VERSION)"
  - if [ -z "$TRAVIS_TAG" ]; then git tag $VERSION; fi
  - zip -r "$VERSION.zip" -@ < ci/include.lst

deploy:
  - provider: releases
    api_key:
      secure: mAG/tSLjKN/M1ltw++L9/ttiMV5B9SfX0o/v+mb3sbaRsvhIcKafKeZDSykGxHN6p2tzmxdaZXPDcE7c7UbFXrZcvm01Vf/Bo9xrTUNpNkwLljnkGYM4FCQixBHSO6znUA9mvLrnKPxc0xR7oEMzY7NlF51UwbJepqY+Kg+zL+EmyBtrDsJoj/NArV8uvtAZlfmlcTfK7T92dVepiJiYhSxeC+AZJgeL9MNqhM596EyO5Er+5iYsX0lEzyUISyERCgiEp+vlvsNuxaizRE1TCkgahGNXWx0Xdrhny5kYvCJ7bqS7TbmyPSG2ysSdSjB/PsgPCQhWISJ94KkqVlrTNhzWLcfUr1M3T2mLOQ0sP8whfAty4At214BOKhKlQZHIPs6Sz0a/KQObmWTCDCqqYj5FeITNhrDQN6DOdJpRzu//BAfkz+2GeWv3Ckq7C/CZRSXWPaz9oqNUKUVOXg6QEo8hVHhXWhVpCNfubSjQtBXJd+GW1cHTuw1xZ9wsOcILe8f0cSv//HiH7ijECZ2PKUp3NV9XfKwR1+KjRR5h+0K5rJRX8F21YkkkQaiFxIkYhyBXxqOiPlPZvdanMbFGL/RYvLy333k2bxNtrKZrEd3oxKZvGJ4GT38BpnQjZJ7cST1/yQD6vtl2GLn0Wt9qAm2rX/6FjYSaeIGKUwro7L8=
    file: $VERSION.zip
    skip_cleanup: true
    on:
      branch: master
      condition: type != pull_request
  - provider: script
    script: aws s3 cp --profile publisher ./$VERSION.zip s3://$CFN_BUCKET/aws-dms-sql-server/$VERSION/aws-dms-sql-server.zip > /dev/null 2>&1
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false

cache: pip
